---
title: "SQL HW"
author: "Ivan Pavlov"
date: "5/4/2017"
output: html_document
---
## Подключаем библиотеки
```{r libs, warning=F, message=F}
library(RSQLite)
library(DBI)
```

## Создаем подключение к БД и достаем информацию
```{r setup}
mydb <- dbConnect(RSQLite::SQLite(), "data.sqlite")
dbListTables(mydb)

# 1) Перечислить пользователей в алфавитном порядке username (все колонки в любом порядке)
head(dbGetQuery(mydb, "SELECT * FROM Users ORDER BY username;"))

# 2) 5 пользователей, которые зарегистрировались последними (все колонки в любом порядке)
dbGetQuery(mydb, "SELECT * FROM Users ORDER BY registered DESC LIMIT 5;")

# 3) Топ 5 пользователей по числу прослушиваний (все колонки в любом порядке)
dbGetQuery(mydb, "SELECT *, COUNT(song_id) 
           FROM Listened 
           INNER JOIN Users ON Listened.user_id = Users.id 
           GROUP BY user_id
           ORDER BY COUNT(song_id) DESC
           LIMIT 5;")

# 4) Информацию об исполнителях и количестве их альбомов (имя исполнителя|число)
head(dbGetQuery(mydb, "SELECT Artists.name, COUNT(Albums.id) AS 'Num. of albums'
           FROM Albums
           INNER JOIN Artists ON Artists.id = Albums.artist_id
           GROUP BY artist_id;"))

# 5) Информацию об исполнителях и количестве их песен (имя исполнителя|число)
head(dbGetQuery(mydb, "SELECT Artists.name, COUNT(Songs.id) AS 'Num. of songs'
           FROM Songs
           INNER JOIN Albums ON Songs.album_id = Albums.id
           INNER JOIN Artists ON Artists.id = Albums.artist_id
           GROUP BY artist_id;"))

# 6) Самый длинный альбом по числу песен. (имя исполнителя|название альбома|число)
dbGetQuery(mydb, "SELECT Artists.name AS artist, Albums.name AS album, COUNT(Songs.id) AS 'Num. of songs'
           FROM Songs
           INNER JOIN Albums ON Songs.album_id = Albums.id
           INNER JOIN Artists ON Artists.id = Albums.artist_id
           GROUP BY Songs.album_id
           ORDER BY COUNT(Songs.id) DESC
           LIMIT 1;")

# 7) Самый длинный альбом по суммарной продолжительности. (имя исполнителя|название альбома|число)
dbGetQuery(mydb, "SELECT Artists.name AS artist, Albums.name AS album, TOTAL(Songs.duration) AS duration
           FROM Songs
           INNER JOIN Albums ON Songs.album_id = Albums.id
           INNER JOIN Artists ON Artists.id = Albums.artist_id
           GROUP BY Songs.album_id
           ORDER BY duration DESC
           LIMIT 1;")

# 8) Альбом самой большой средней продолжительностью трека. (имя исполнителя|название альбома|число)
dbGetQuery(mydb, "SELECT Artists.name AS artist, Albums.name AS album, AVG(Songs.duration) AS mean_song_duration
           FROM Songs
           INNER JOIN Albums ON Songs.album_id = Albums.id
           INNER JOIN Artists ON Artists.id = Albums.artist_id
           GROUP BY Songs.album_id
           ORDER BY mean_song_duration DESC
           LIMIT 1;")

# 9) Топ 5 самых прослушиваемых треков. (имя исполнителя|название альбома|название песни|число)
dbGetQuery(mydb, "SELECT Artists.name AS artist, Albums.name AS album, Songs.name AS song, COUNT(Listened.song_id) AS listened
           FROM Songs
           INNER JOIN Albums ON Songs.album_id = Albums.id
           INNER JOIN Artists ON Artists.id = Albums.artist_id
           INNER JOIN Listened ON Listened.song_id = Songs.id
           GROUP BY Songs.id
           ORDER BY listened DESC
           LIMIT 5;")

# 10) Найдите год, что песни, выпущенные в этом году, слушают больше всего (год|количество прослушиваний)
dbGetQuery(mydb, "SELECT Albums.release_year AS year, COUNT(Listened.song_id) AS listened
           FROM Songs
           INNER JOIN Albums ON Songs.album_id = Albums.id
           INNER JOIN Artists ON Artists.id = Albums.artist_id
           INNER JOIN Listened ON Listened.song_id = Songs.id
           GROUP BY Albums.release_year
           ORDER BY listened DESC
           LIMIT 1;")

# 11) Для пользователя с id=47 найдите топ 20 последних прослушанных треков. (имя исполнителя|название альбома|название песни|когда)
head(dbGetQuery(mydb, "SELECT Artists.name AS artist, Albums.name AS album, Songs.name AS song, Listened.start_time AS time
           FROM Songs
           INNER JOIN Albums ON Songs.album_id = Albums.id
           INNER JOIN Artists ON Artists.id = Albums.artist_id
           INNER JOIN Listened ON Listened.song_id = Songs.id
           WHERE Listened.user_id = 47
           ORDER BY time DESC
           LIMIT 20;"))

# 12) Для каждого пользователя и каждой песни, которую пользователь прослушал, найдите количество прослушиваний. (имя пользователя|имя исполнителя|название альбома|название песни|число)
head(dbGetQuery(mydb, "SELECT Users.username AS user, Artists.name AS artist, Albums.name AS album, Songs.name AS song, COUNT(Listened.song_id) AS listened
           FROM Songs
           INNER JOIN Albums ON Songs.album_id = Albums.id
           INNER JOIN Artists ON Artists.id = Albums.artist_id
           INNER JOIN Listened ON Listened.song_id = Songs.id
           INNER JOIN Users ON Users.id = Listened.user_id
           GROUP BY Users.id, Songs.id
           ORDER BY user;"))

```